"""add description column

Revision ID: 094f3d13f5c0
Revises: 46d1027d6b9c
Create Date: 2026-05-23 08:24:10.093100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094f3d13f5c0'
down_revision: Union[str, Sequence[str], None] = '46d1027d6b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'description')
    # ### end Alembic commands ###
